"""Shared constants for the agent log analysis service."""

from __future__ import annotations

HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_UNAVAILABLE = 503

ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_EVENT_CONFLICT = "EVENT_ID_CONFLICT"
ERROR_EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
ERROR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

MAX_LABEL_KEY_LENGTH = 64
MAX_LABEL_VALUE_LENGTH = 256
MAX_AGGREGATE_GROUP_KEYS = 3
