from __future__ import annotations

DRIVER_KEY = "driver"
IMAGE_KEY = "image"
DOCKER = "docker"
RUN_COMMAND = "run"
DETACHED_FLAG = "-d"
OPENAI_API_KEY = "OPENAI_API_KEY"
RUN_PATH = "core.orchestra_agents.docker_driver.driver._run"
CODING_AGENT_CONTAINER = "orchestra-agent-coding_agent"
EXISTS_KEY = "exists"
HEALTHY_KEY = "healthy"
STATUS_KEY = "status"
RUNNING_KEY = "running"
AGENT_IMAGE = "agent-image:latest"
SGR_RUNTIME_IMAGE = "orchestra-sgr-runtime:latest"
MUX_RUNTIME_IMAGE = "orchestra-agent-mux-runtime:latest"
OPENCODE_RUNTIME_IMAGE = "orchestra-opencode-runtime:latest"
COMPOSE_PROJECT = "orchestrathreads-test"
COMPOSE_ENV_KEY = "ORCHESTRA_AGENTS_COMPOSE_PROJECT_NAME"
COMPOSE_FILE_NAME = "coding_agent.yaml"
